// Code generated by Clue Mock Generator v1.2.3, DO NOT EDIT.
//
// Command:
// $ cmg gen goa.design/pulse/examples/weather/services/poller/clients/nominatim

package mocknominatim

import (
	"context"
	"testing"

	"goa.design/clue/mock"

	"goa.design/pulse/examples/weather/services/poller/clients/nominatim"
)

type (
	Client struct {
		m *mock.Mock
		t *testing.T
	}

	ClientSearchFunc func(ctx context.Context, query string) ([]*nominatim.Location, error)
	ClientNameFunc   func() string
	ClientPingFunc   func(ctx context.Context) error
)

func NewClient(t *testing.T) *Client {
	var (
		m                  = &Client{mock.New(), t}
		_ nominatim.Client = m
	)
	return m
}

func (m *Client) AddSearch(f ClientSearchFunc) {
	m.m.Add("Search", f)
}

func (m *Client) SetSearch(f ClientSearchFunc) {
	m.m.Set("Search", f)
}

func (m *Client) Search(ctx context.Context, query string) ([]*nominatim.Location, error) {
	if f := m.m.Next("Search"); f != nil {
		return f.(ClientSearchFunc)(ctx, query)
	}
	m.t.Helper()
	m.t.Error("unexpected Search call")
	return nil, nil
}

func (m *Client) AddName(f ClientNameFunc) {
	m.m.Add("Name", f)
}

func (m *Client) SetName(f ClientNameFunc) {
	m.m.Set("Name", f)
}

func (m *Client) Name() string {
	if f := m.m.Next("Name"); f != nil {
		return f.(ClientNameFunc)()
	}
	m.t.Helper()
	m.t.Error("unexpected Name call")
	return ""
}

func (m *Client) AddPing(f ClientPingFunc) {
	m.m.Add("Ping", f)
}

func (m *Client) SetPing(f ClientPingFunc) {
	m.m.Set("Ping", f)
}

func (m *Client) Ping(ctx context.Context) error {
	if f := m.m.Next("Ping"); f != nil {
		return f.(ClientPingFunc)(ctx)
	}
	m.t.Helper()
	m.t.Error("unexpected Ping call")
	return nil
}

func (m *Client) HasMore() bool {
	return m.m.HasMore()
}
