#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}

./scripts/setup
./scripts/start-redis
./scripts/test

# This is a bit too slow for CI
# ./scripts/run-examples

popd
