#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}/examples/weather

echo "Starting diagram editor..."

mdl serve goa.design/pulse/examples/weather/diagram -dir diagram -port 8095 forecaster

popd