#!/usr/bin/env bash

set -e

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}

source ./scripts/utils/common.sh

# Requires carbon-now-cli v2
# https://github.com/mixn/carbon-now-cli/tree/v2
check_required_cmd "carbon-now" "carbon-now-cli"

carbon() {
        local input_file="$1"
        local start_line="$2"
        local end_line="$3"
        local output_file="$4"
        
        carbon-now "$input_file" \
                --start "$start_line" \
                --end "$end_line" \
                --config snippets/carbon-config.json \
                --preset "ponos" \
                --save-as "snippets/$output_file"
}

carbon examples/rmap/basics/main.go  24   29  "rmap-join"
carbon examples/rmap/basics/main.go  41   46  "rmap-set"
carbon examples/rmap/basics/main.go  60   72  "rmap-append"
carbon examples/rmap/basics/main.go  79   84  "rmap-inc"
carbon examples/rmap/basics/main.go  48   53  "rmap-delete"
carbon examples/rmap/basics/main.go  31   34  "rmap-reset"
carbon examples/rmap/basics/main.go  86   88  "rmap-get"
carbon examples/rmap/basics/main.go  90   92  "rmap-keys"
carbon examples/rmap/basics/main.go  94   96  "rmap-len"
carbon examples/rmap/basics/main.go  98   100 "rmap-map"
carbon examples/rmap/basics/main.go  102  103 "rmap-subscribe"
carbon examples/rmap/basics/main.go  104  104 "rmap-unsubscribe"

carbon examples/streaming/single-reader/main.go  21  51 "single-reader"
carbon examples/streaming/multi-readers/main.go  45  72 "multi-reader"
carbon examples/streaming/single-sink/main.go    37  56 "single-sink"
carbon examples/streaming/multi-sinks/main.go    58  79 "multi-sink"
carbon examples/streaming/multi-streams/main.go  61  62 "multi-stream"
carbon examples/streaming/multi-streams/main.go  87  91 "remove-stream"
carbon examples/streaming/pub-sub/main.go        31  35 "pub-sub"
carbon examples/streaming/pub-sub/main.go        76  79 "pub-sub-pattern"
carbon examples/streaming/pub-sub/main.go        94  99 "pub-sub-matcher"

carbon examples/pool/worker/main.go     43   47  "pool-addnode"
carbon examples/pool/producer/main.go   31   36  "pool-close"
carbon examples/pool/worker/main.go     62   64  "pool-shutdown"
carbon examples/pool/worker/main.go     55   57  "pool-addworker"
carbon pool/worker.go                   59   72  "worker-jobhandler"
carbon examples/pool/producer/main.go   38   42  "pool-dispatchjob"
popd
