#!/usr/bin/env bash

set -e

echo "Running tests..."

GIT_ROOT=$(git rev-parse --show-toplevel)
pushd ${GIT_ROOT}

staticcheck ./...

# Run tests one package at a time to avoid Redis race conditions
go test -race goa.design/ponos/rmap/... 
go test -race goa.design/ponos/streaming/...
go test -race goa.design/ponos/pool/...

popd
